"""empty message

Revision ID: 28fc82d76271
Revises: 
Create Date: 2019-03-01 14:59:20.810627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fc82d76271'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.drop_constraint('companies_name_key', 'companies', type_='unique')
    op.drop_constraint('companies_symbol_key', 'companies', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('companies_symbol_key', 'companies', ['symbol'])
    op.create_unique_constraint('companies_name_key', 'companies', ['name'])
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    # ### end Alembic commands ###
