"""empty message

Revision ID: a9628bb723c3
Revises: 83dba0fcbba4
Create Date: 2019-03-10 19:13:58.030623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9628bb723c3'
down_revision = '83dba0fcbba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'user_id')
    # ### end Alembic commands ###
