"""empty message

Revision ID: d18e570b2e06
Revises: 4b7d54a0550f
Create Date: 2019-03-07 18:03:05.576903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18e570b2e06'
down_revision = '4b7d54a0550f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_column('portfolios', 'user_id')
    # ### end Alembic commands ###
